server:
  port: 8090
security:
  oauth2:
    resource:
      id: employee-service
      jwt:
        key-value: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgchNRxaNNH74OA4snaAH\ndrTJPqvwPNcD1pF2uYRBqpGBa/IJpQ7tDfs326mz/eoww4tcW0hQ7HBSE54Zr3E3\n6iX59rgJUEzOJxsMxBxLTjkRjYohSIgZQoHZDyKv/O/XGcXmmNXsUrhF+1/FDE9o\nKd100hOYxJNOX1IQmoGfkXCfw9Om4h+qL9XsWarmaZRRndGFBW8EpdzYlYl3h6al\n9hGf1RCkokjWQkX+9EEBKC9ek5iuaWZqgVvZlhkqtShsjpA9odV3Yt504rAjc2+R\nn3rrZJzc02ycsHXmJ0NGLEqSOWsXbnbh/ifMnBQap0UnBNqS4E7HQaKbX15pNrHK\njQIDAQAB\n-----END PUBLIC KEY-----"    client:      client-id: employee-service      client-secret: abc123      user-authorization-uri: ${rest.security.issuer-uri}/oauth/authorize      access-token-uri: ${rest.security.issuer-uri}/oauth/token      grant-type: client_credentials      scope:      - EMPLOYEE
      - DEPARTMENT
rest.security.enabled: true
rest.security.api-matcher: /api/**
rest.security.cors.allowed-origins: "*"
rest.security.cors.allowed-headers: "*"
rest.security.cors.allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
rest.security.cors.max-age: 3600
rest.security.issuer-uri: http://localhost:8081/spring-security-oauth-server